###
#
# This workflow file is deployed into this repository via the "Sync PHPCS Organization File" workflow
#
# Direct edits to this file are at risk of being overwritten by the next sync. All edits should be made
# to the source file.
#
# @see Sync workflow {@link https://github.com/caseproof/.github/workflows/workflow-phpcs-sync.yml}
# @see Workflow template {@link https://github.com/caseproof/.github/blob/main/.github/workflow-templates/phpcs.yml}
#
###
name: PHP Coding Standards

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ 'pull_request' == github.event_name && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    name: PHP Coding Standards

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ fromJson(vars.PHP_VERSIONS)[0] }} # Run on lowest supported PHP version so we don't implement features that are not supported.
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        env:
          COMPOSER_AUTH: '{"github-oauth":{"github.com":"${{secrets.CSPF_REPO_READ_PAT}}"}}'
        run: composer update

      - name: Check CS on PR
        if: github.event_name == 'pull_request'
        run: composer run cs-check -- --runtime-set ignore_warnings_on_exit true -- `gh pr diff ${{ github.event.number }} --name-only 2> /dev/null`

      - name: Check CS
        if: github.event_name != 'pull_request'
        run: composer run cs-check -- --runtime-set ignore_warnings_on_exit true
