name: Create recurring tasks

on: 
  schedule:
    - cron: 0 0 * * MON # Every week on Monday at midnight UTC.
  workflow_dispatch:  

jobs:
  create-issue:
    name: Create issue
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:

      - name: Create issue
        env:
          GH_TOKEN: ${{ secrets.IPJ_ISSUE_MANAGE_PAT }}
          GH_REPO: ${{ github.repository }}
          TITLE: '[Recurring] Plugin and Theme updates'
          BODY: |
            Perform Plugin and Theme updates on the website.
            Due by: $(date -d "next fri 22 UTC")
            Due by: $(date -d "+2 weeks")
        run: |
          PREV_ISSUE_NUM=$(gh issue list --search "$TITLE" --state open --json number --jq '.[0].number')
          if [[ -n $PREV_ISSUE_NUM ]]; then
            echo "An issue already exists for "$TITLE", see issue #$PREV_ISSUE_NUM"
          else
            gh issue create --title "$TITLE" --body "$BODY"
          fi
